# Generated by Django 4.1.7 on 2023-03-11 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Edad', models.IntegerField(verbose_name=2)),
                ('Fecha', models.DateTimeField(verbose_name='Fecha de registro')),
            ],
        ),
    ]
