# Generated by Django 4.1.7 on 2023-03-11 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_prestamos', '0002_alter_cliente_edad_prestamo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='interes',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='total_pago',
            field=models.FloatField(),
        ),
    ]
